version: "3.9"

services:
  list:
    build: .
    container_name: lista-list
    ports:
      - "9000:9000"
    depends_on:
      - postgres
  add:
    build: .
    container_name: lista-add
    command: node add.js
    ports:
      - "9001:9001"
    depends_on:
      - list

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: control
    ports:
      - "5432:5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
